// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5UATIWXJen455bTl624kWs3gdMkoCs14',
    appId: '1:380796381736:web:3cd2f48337670d184e631d',
    messagingSenderId: '380796381736',
    projectId: 'jorgepantoja9b',
    authDomain: 'jorgepantoja9b.firebaseapp.com',
    storageBucket: 'jorgepantoja9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeH7-tzmEXMAPxrVQEmyfCDHMBD5eVBmA',
    appId: '1:380796381736:android:480aeb338b990bec4e631d',
    messagingSenderId: '380796381736',
    projectId: 'jorgepantoja9b',
    storageBucket: 'jorgepantoja9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdqZQaeKDkrmw4wBhGMQV9i2ot9wzU45E',
    appId: '1:380796381736:ios:8e05ab4c37c4f0c34e631d',
    messagingSenderId: '380796381736',
    projectId: 'jorgepantoja9b',
    storageBucket: 'jorgepantoja9b.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
